export const ADD_WORD = 'ADD_WORD'
export const DELETE_WORD = 'DELETE_WORD'
export const DELETE_WORDS = 'DELETE_WORDS'
export const UPDATE_WORD = 'UPDATE_WORD'
export const HIGHLIGHT_WORD = 'HIGHLIGHT_WORD'

export const ADD_COLLECTION = 'ADD_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION'
export const CHOOSE_COLLECTION = 'CHOOSE_COLLECTION'

export const INCREASE_TOTAL_WORD_COUNT = 'INCREASE_TOTAL_WORD_COUNT'
export const DECREASE_TOTAL_WORD_COUNT = 'DECREASE_TOTAL_WORD_COUNT'
export const UPDATE_TOTAL_WORD_COUNT = 'UPDATE_TOTAL_WORD_COUNT'
export const INCREASE_COLLECTION_WORD_COUNT = 'INCREASE_COLLECTION_WORD_COUNT'
export const DECREASE_COLLECTION_WORD_COUNT = 'DECREASE_COLLECTION_WORD_COUNT'
export const UPDATE_CURRENT_COLLECTION_WORD_COUNT = 'UPDATE_CURRENT_COLLECTION_WORD_COUNT'
export const SET_COLLECTION_WORD_COUNT = 'SET_COLLECTION_WORD_COUNT'

export const DISPLAY_RECALL_WORDS = 'DISPLAY_RECALL_WORDS'
export const HIDE_RECALL_WORDS = 'HIDE_RECALL_WORDS'

export const INPUT_MAX_LENGTH = '30'